{% set name = "ome-zarr" %}
{% set version = "0.19.1" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ba0e44e22ede92221d03f3a6f18ebfabb6b4b8c1ea7cd54c7b697f76d6d61288

build:
  number: 0
  noarch: python
  entry_points:
    - ome_zarr = ome_zarr.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=77.0.3
    - setuptools-scm >=8.0
  run:
    - transformnd >=0.6.0,<0.8.0
    - ome-zarr-models >=1.8.1
    - deprecated
    - rangehttpserver
    - aiohttp
    - dask-core >=2025.2.0,!=2025.12.*,!=2026.1.*,!=2026.2.*
    - fsspec >=0.8,!=2021.07.0,!=2023.9.0
    - numpy
    - python >={{ python_min }}
    - requests
    - scikit-image >=0.19.0
    - toolz
    - zarr >=3.0.0

test:
  imports:
    - ome_zarr
  commands:
    - python -c "import importlib.metadata; print(importlib.metadata.version('ome_zarr'))" | grep -q {{ version }}
    - pip check
    - ome_zarr --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ome/ome-zarr-py
  summary: Implementation of images in Zarr files.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - joshmoore
    - k-dominik
    - jdblischak
    - will-moore
    - jo-mueller
